version: '3.8'

services:
  # --- Vector Database ---
  qdrant:
    image: qdrant/qdrant:latest
    container_name: rag-qdrant
    ports:
      - "6333:6333"
    volumes:
      - ./qdrant_data:/qdrant/storage

  # --- Message Broker for Celery ---
  redis:
    image: redis:7-alpine
    container_name: rag-redis
    ports:
      - "6379:6379"

  # --- Local LLM Server ---
  ollama:
    image: ollama/ollama:latest
    container_name: rag-ollama
    ports:
      - "11434:11434"
    volumes:
      - ./ollama_data:/root/.ollama
    # If you have an NVIDIA GPU, uncomment the lines below to use it:
    # deploy:
    #   resources:
    #     reservations:
    #       devices:
    #         - driver: nvidia
    #           count: 1
    #           capabilities: [gpu]

  # --- FastAPI Main App ---
  api:
    build: .
    container_name: rag-api
    ports:
      - "8000:8000"
    environment:
      - REDIS_URL=redis://redis:6379/0
      - QDRANT_HOST=qdrant
      - OLLAMA_BASE_URL=http://ollama:11434
    depends_on:
      - qdrant
      - redis
      - ollama
    command: uvicorn main:app --host 0.0.0.0 --port 8000 --reload
    volumes:
      - ./storage:/app/storage # Shared storage for uploaded files

  # --- Celery Worker (The Muscle) ---
  worker:
    build: .
    container_name: rag-worker
    environment:
      - REDIS_URL=redis://redis:6379/0
      - QDRANT_HOST=qdrant
    depends_on:
      - redis
      - qdrant
    # This command starts the background worker
#    command: celery -A app.core.celery_app worker --loglevel=info
    command: celery -A app.core.celery_app:celery_app worker --loglevel=info 
    volumes:
      - ./storage:/app/storage # Must match API storage


  frontend:
      build: ./frontend
      container_name: rag-frontend
      ports:
        - "5173:5173"
      depends_on:
        - api
